spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: ga
    password:
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true